packages/upload-api/src/types.ts
packages/upload-api/src/upload/add.js
packages/upload-api/test/storage/upload-table.js

Materially this is a rename, but infra was not recording this value and it will do now, so this change is non breaking.

fix: record upload add cause

---

packages/capabilities/package.json
packages/capabilities/src/blob.js
packages/capabilities/test/capabilities/blob.test.js
packages/upload-api/src/blob/accept.js
packages/upload-api/src/blob/add.js
packages/upload-api/src/blob/get.js
packages/upload-api/src/blob/list.js
packages/upload-api/src/types.ts
packages/upload-api/src/types/blob.ts
packages/upload-api/test/external-service/index.js
packages/upload-api/test/external-service/storage-node.js
packages/upload-api/test/handlers/blob.js
packages/upload-api/test/storage/blob-registry-tests.js
packages/upload-api/test/storage/blob-registry.js
packages/upload-api/test/storage/usage-storage.js
packages/upload-client/test/helpers/utils.js
pnpm-lock.yaml

Not string, it bytes! It has a compact byte encoding.

fix: encode space DID as bytes in blob caveats

---

packages/w3up-client/src/client.js

Part of https://github.com/storacha/project-tracking/issues/140
Fix references to types. These were both referring to the entire _modules_, rather than to the correct types within those modules.

fix: Fix type references

---

.github/release-please-manifest.json
packages/w3up-client/CHANGELOG.md
packages/w3up-client/package.json

Reverts storacha/upload-service#79
Release didn't work. Going to try to revert and re-revert to poke Release Please.

chore: Revert "chore(main): release client 1.0.3"

---

packages/capabilities/src/space.js
packages/capabilities/src/types.ts
packages/capabilities/src/usage.js
packages/capabilities/test/helpers/fixtures.js
packages/upload-api/src/space.js
packages/upload-api/src/space/record.js
packages/upload-api/src/usage.js
packages/upload-api/test/helpers/utils.js
packages/w3up-client/src/capability/space.js
packages/w3up-client/src/capability/usage.js
packages/w3up-client/test/capability/space.test.js
packages/w3up-client/test/capability/usage.test.js

This PR restructures the `usage/record` capability, moving it under the `Space` namespace instead of `Usage`. As part of this change, the `usage/record` definition has been renamed to
`space/content/serve/egress/record`, and a new top-level capability, `space/content/serve/*`, has been introduced.
- **Namespace Update**: The `usage/record` capability now resides under the `Space` namespace.
- **New Naming Convention**:
- `space/content/serve/egress/record`: This capability records egress for all served data.
- `space/content/serve/*`: New top-level capability, representing general serve actions within the `Space.contentServe` namespace.
---------

fix(egress/record): rename capability (#1572)

---

packages/capabilities/src/types.ts
packages/cli/bin.js
packages/cli/index.js
packages/cli/space.js
packages/cli/test/bin.spec.js
packages/filecoin-api/src/aggregator/events.js
packages/upload-api/src/access/claim.js
packages/upload-api/src/lib.js
packages/upload-api/test/helpers/utils.js
packages/w3up-client/package.json
packages/w3up-client/src/client.js
packages/w3up-client/src/index.js
packages/w3up-client/src/types.ts
packages/w3up-client/test/account.test.js
packages/w3up-client/test/capability/access.test.js
packages/w3up-client/test/capability/blob.test.js
packages/w3up-client/test/capability/filecoin.test.js
packages/w3up-client/test/capability/index.test.js
packages/w3up-client/test/capability/space.test.js
packages/w3up-client/test/capability/subscription.test.js
packages/w3up-client/test/capability/upload.test.js
packages/w3up-client/test/capability/usage.test.js
packages/w3up-client/test/client.test.js
packages/w3up-client/test/coupon.test.js
packages/w3up-client/test/helpers/gateway-server.js
packages/w3up-client/test/mocks/service.js
packages/w3up-client/test/space.test.js
pnpm-lock.yaml

To enable a gateway to serve content from a specific space, we must ensure that the space owner delegates the `space/content/serve/*` capability to the Gateway. This delegation allows the Gateway to serve content and log egress events appropriately.
I created a new function `authorizeContentServe` for this implementation and included it in the `createSpace` flow. This is a breaking change because now the user is forced to provide the DIDs of the Content Serve services, and the connection, or skip the authorization flow.
Additionally, with the `authorizeContentServe` function, we can implement a feature in the Console App that enables users to explicitly authorize the Freeway Gateway to serve content from existing/legacy spaces.
- **New Functionality:** 
- Added a new function, …

feat: content serve authorization (#1590) + set default gateway

---

packages/capabilities/src/filecoin/index.js
packages/capabilities/src/filecoin/storefront.js
packages/capabilities/src/types.ts
packages/w3up-client/src/client.js
packages/w3up-client/test/capability/space.test.js

- Added the Filecoin top-level capability.
- Updated w3up-client to use it instead of defining all of the filecoin capabilities.
Resolves: https://github.com/storacha/w3up/issues/1554

chore(capabilities): top level filecoin cap

---

packages/w3up-client/src/client.js

The `options` field should be optional, and if not set, we still want to grant access to Storacha Gateway to serve the content of the space.

fix(w3up-client): create space options

---

packages/w3up-client/src/client.js

We need to save the space before setting it as the current space, otherwise the authorization flow will fail because the agent won't be allowed to use that space.

fix(w3up-client): authorize agent to use space

---

packages/upload-api/package.json
packages/upload-api/src/lib.js
packages/upload-api/src/types.ts
packages/upload-api/test/helpers/context.js
packages/upload-api/test/storage/agent-store.js
pnpm-lock.yaml

This PR adds the legacy `store/*` and `admin/store/inspect` handlers from the `@web3-storage/upload-api` in order to support deprecated actions for a bit longer, per https://github.com/storacha/RFC/pull/38
refs https://github.com/storacha/project-tracking/issues/268

feat: add legacy handlers

---

packages/upload-api/src/blob/remove.js
packages/upload-api/src/types/blob.ts
packages/upload-api/test/storage/blob-registry-tests.js
packages/upload-api/test/storage/blob-registry.js

The new blob/remove flow introduced in https://github.com/storacha/w3infra/pull/458 removes the ucan-stream (https://github.com/storacha/project-tracking/issues/304)  and updates the space-diff table directly from the blob-registry.
To properly create a space-diff entry in deregister, the invocation CID is required. However, unlike register, it is not currently passed as a parameter. This update ensures the necessary data is available for consistent and accurate tracking of space usage.

refactor: add cause as a param to deregister

---

packages/upload-client/src/blob/add.js

Was referencing the result from blob add not the result from UCAN conclude 🤦

fix: use correct object in cause

---

packages/access-client/test/agent-use-cases.test.js
packages/capabilities/test/capabilities/provider.test.js
packages/capabilities/test/helpers/fixtures.js
packages/cli/README.md
packages/cli/test/bin.spec.js
packages/filecoin-api/src/aggregator/events.js
packages/upload-api/src/blob/remove.js
packages/upload-api/src/lib.js
packages/upload-api/src/types.ts
packages/upload-api/src/types/blob.ts
packages/upload-api/test/handlers/plan.js
packages/upload-api/test/helpers/context.js
packages/upload-api/test/storage/blob-registry-tests.js
packages/upload-api/test/storage/blob-registry.js
packages/upload-api/test/storage/provisions-storage.js
packages/upload-api/test/util.js
packages/upload-client/src/service.js
packages/w3up-client/src/service.js
packages/w3up-client/test/client.test.js
packages/w3up-client/test/coupon.test.js
scripts/mkdelegate.js

We decided to use the existing URL and DID i.e. `up.storacha.network` not `upload.storacha.network`. This PR updates the values.

fix: use up.storacha.network

---

packages/access-client/src/agent.js
packages/access-client/test/agent.test.js

This PR dedupes proofs returned by a call to `.proofs(...)`. i.e. if the same delegation proves multiple capabilities then it is not included multiple times in the returned array.
This will produce slightly smaller delegations as the UCANs issued will not have multiple entries for the same CID. For example, see `prf` field in UCAN below:
```
bafyreifv6bo5mbxwpzlvpnpflyjtndmxgp5fznzqudshlhhjv3jhvlkabu
{
"att": [
{
"can": "space/*",
"with": "did:key:z6MkutRMwQSS2posWavyTPb6aFnZUA9rFq64hHZ9r6ZCQe4P"
},
{
"can": "blob/*",
"with": "did:key:z6MkutRMwQSS2posWavyTPb6aFnZUA9rFq64hHZ9r6ZCQe4P"
},
{
"can": "index/*",
"with": "did:key:z6MkutRMwQSS2posWavyTPb6aFnZUA9rFq64hHZ9r6ZCQe4P"
},
{
"can": "store/*",
"with": "did:key:z6MkutRMwQSS2posWavyTPb6aFnZUA9rFq64hHZ9r6ZCQe4P"
},
{
"can": "upload/*", …
```

fix: dedupe proofs

---

packages/upload-api/src/blob/accept.js
packages/upload-api/src/blob/add.js

w3infra currently requires all receipts in agent messages to have corresponding invocations. This PR simply adds the fake w3s accept invocation for the (already added) w3s accept receipt to the agent message so that this requirement can be met.
This also fixes an issue with registering blobs when a blob already exists on a storage node.

fix: store w3s accept invocation

---

nx.json

This config was missing from the `nx.json`, blocking releases.

Enable changelogs

---

packages/ui/packages/eslint-config/package.json

Otherwise, pnpm can't resolve the `workspace:` references to it during publish.

`@storacha/eslint-config-ui` needs a version

---

nx.json

No comments in JSON. Resolves:
```console
$ npx nx release plan
NX   There was an error when resolving the configured changelog renderer at path: node_modules/.pnpm/nx@20.3.2_@swc+core@1.10.11_@swc+helpers@0.5.15_/node_modules/nx/release/changelog-renderer
The relevant config is defined here: ../../nx.json, lines 40-53
NX   Cannot read properties of undefined (reading 'map')
Pass --verbose to see the stacktrace.
```

fix: remove comments from nx config

---

packages/access-client/package.json
packages/blob-index/package.json
packages/capabilities/package.json
packages/cli/package.json
packages/did-mailto/package.json
packages/filecoin-client/package.json
packages/ui/packages/core/package.json
packages/ui/packages/react/package.json
packages/upload-api/package.json
packages/upload-client/package.json
packages/w3up-client/package.json

Otherwise, they're treated as private by default.

Make all published packages public

---

.github/workflows/ci.yml
.nx/version-plans/version-plan-1742834795328.md
packages/ui/examples/react/components/package.json
packages/ui/packages/core/package.json
packages/ui/packages/react/package.json
pnpm-lock.yaml
pnpm-workspace.yaml

Note that the build result is now slightly different, as we don't produce an `index.js` and an `index.esm.js` However, they were both already ESM (note that both packages are `"type": "module"`); the difference was that one was bundled into a single module and the other was not. This change _should_ be transparent to downstream packages. Any noticeable difference is a bug that should be addressed.
Note that the downstream packages in the monorepo are building fine.

fix: Exorcise `bunchee` and reinstate CI parallelism

---

.nx/version-plans/version-plan-1743186518893.md
packages/ui/packages/react/src/Authenticator.tsx

Otherwise, if this component comes into existence while `client` is `undefined`, it will *always* be `undefined`.

fix: `handleRegisterSubmit` needs to depend on `client`

---

packages/w3up-client/package.json
packages/w3up-client/src/base.js
packages/w3up-client/src/service.js
pnpm-lock.yaml
pnpm-workspace.yaml

- Updated the `@ucanto/transport` lib to `9.2.0` - which supports custom headers in HTTP transport channels
- Updated the Access client to support custom headers in the channel creation, connection, and Agent constructor.
- Tests

feat(access-client): allow custom headers in the agent

---

.nx/version-plans/version-plan-1744045376500.md
packages/w3up-client/src/index.node.js

Was exported in the browser but not Node.js.

fix: export authorizeContentServe in Node.js

---

packages/capabilities/src/utils.js

As per [this thread](https://github.com/storacha/go-libstoracha/pull/11#discussion_r2025173396) in the PR adding the Go version of this capability it looks like the check for body size in the `http/put` capability could be copied over from a similar escalation check in the `store/add` capability. However, while allowing a client to upload less data makes sense in `store/add`, it doesn't in `http/put`.

fix: strict comparison of body size in http/put capability

---

packages/upload-client/src/index.js

In The Telegram miniapp we're creating a block stream and serializing it to a CAR file which is then immeidately deserialized for sharding. This allows us to skip that useless work.

feat: export uploadBlockStream

---

.nx/version-plans/version-plan-1746096228972.md
packages/cli/README.md
packages/cli/bin.js
packages/cli/index.js
packages/upload-client/README.md
packages/upload-client/src/types.ts
packages/w3up-client/README.md

Functionality was removed a long time ago but option was never cleaned up properly.

fix: remove unused option for concurrent requests

---

.nx/version-plans/version-plan-1746652670170.md
packages/ui/packages/react/src/hooks.ts

This marks state changes as lower priority, so (eg.) updating the list of spaces doesn't interrupt more immediate UI feedback.
This is what's causing https://github.com/storacha/project-tracking/issues/418.

Use `startTransition` in the hook implementations

---

.nx/version-plans/version-plan-1747092295287.md
packages/upload-client/src/car.js
packages/upload-client/src/index.js
packages/upload-client/src/sharding.js
packages/upload-client/src/types.ts
packages/upload-client/test/index.test.js

This is a backward compatible change that allows for faster uploads for files with total size less than the shard size limit.
Measurements show that sequential `blob/add`+`http/put`+`ucan/conclude` for both the data and the index is slowing the process down significantly:
```sh
$ echo 'alantest 2025-05-12-1' | w3 up
created shard: 4.414ms
hashing shard: 0.013ms
invoking blob/add: 1.522s
invoking http/put: 181.018ms
invoking ucan/conclude http/put: 935.68ms
polling for receipt: 1.081s
hashing piece: 54.925ms
invoking filecoin/offer: 460.332ms
invoking blob/add: 1.216s
invoking http/put: 115.911ms
invoking ucan/conclude http/put: 1.164s
polling for receipt: 382.596ms
invoking index/add: 1.252s
invoking upload/add: 614.062ms
total: 9.000s
⁂ Stored 1 file
⁂ …
```

perf: faster small file uploads

---

packages/cli/account.js
packages/cli/lib.js
packages/cli/space.js

When using `storacha login [email]` if you do not provide your email address it asks you how you want to login, but if you select email it tells you to run the command again passing your email address. That kinda sucks - instead, prompt the user to add their email address and then continue login.

fix: prompt for email if not provided

---

packages/capabilities/package.json
packages/capabilities/src/assert.js
packages/capabilities/src/index.js
packages/capabilities/src/space/blob.js
packages/capabilities/src/types.ts
packages/capabilities/src/utils.js
packages/capabilities/test/capabilities/assert.test.js
packages/capabilities/test/capabilities/provider.test.js
packages/upload-api/src/test/handlers/ucan.js
pnpm-lock.yaml

This PR adds the `assert/*` capabilities from the legacy `@web3-storage/content-claims/capability` to `@storacha/capabilities/assert`.
Content claims are part of the Storacha system, used by the upload service, indexer and gateway.
Also adds tests for the 3 claims we actually use `assert/equals`, `assert/index` and `assert/location`

feat: add `assert/*` capabilities

---

packages/cli/index.js

Fixes a couple of instances where we throw a known error instead of logging the reason and existing with error code.
For these kinds of errors a stack trace is not useful.

fix(cli): nicer errors

---

packages/upload-api/src/index/add.js
packages/upload-api/src/types/index.ts

This allows publishing to IPNI for external discovery to be optional. The warm storage network will not facilitate external discovery.

feat: allow IPNI service to be optional

---

.nx/version-plans/version-plan-1748976116053.md
packages/w3up-client/src/account.js
packages/w3up-client/test/account.test.js

- The polling function (`plan.wait()`) now continues polling when a `PlanNotFound` error is returned, instead of throwing an error and interrupting the flow.
- The function only throws for unexpected errors, timeout, or when the abort signal is triggered.

fix: improve plan polling to not throw immediately on PlanNotFound

---

packages/w3up-client/README.md

This PR fixes broken links and improves diagram compatibility in the `w3up-client/README.md` file for the `@storacha/client` package.
- Corrected typo in UCAN link (`ucan.xzy` → `ucan.xyz`)
- Fixed malformed markdown link for Integration Options
- Replaced insecure `http://storacha.network` with `https://`
- Fixed mermaid diagram code 
- Screenshot: 
Closes #281

[DOC]: Fix Broken links & mermaid diagram in w3up-client/README

---

packages/encrypt-upload-client/README.md
packages/encrypt-upload-client/examples/decrypt-test.js
packages/encrypt-upload-client/examples/encrypt-test.js
packages/encrypt-upload-client/lit-actions/validate-decrypt-invocation.js
packages/encrypt-upload-client/package.json
packages/encrypt-upload-client/src/config/constants.js
packages/encrypt-upload-client/src/config/env.js
packages/encrypt-upload-client/src/config/service.js
packages/encrypt-upload-client/src/core/client.js
packages/encrypt-upload-client/src/crypto-adapters/browser-crypto-adapter.js
packages/encrypt-upload-client/src/crypto-adapters/node-crypto-adapter.js
packages/encrypt-upload-client/src/handlers/decrypt-handler.js
packages/encrypt-upload-client/src/handlers/encrypt-handler.js
packages/encrypt-upload-client/src/index.js
packages/encrypt-upload-client/src/protocols/lit.js
packages/encrypt-upload-client/src/types.ts
packages/encrypt-upload-client/test/browser-crypto-adapter.spec.js
pnpm-lock.yaml

- **Added BrowserCryptoAdapter**  
New adapter using the Web Crypto API for browser encryption/decryption and using `AES-CTR` to make it compatible with Browsers and support content streaming.
- **Async CryptoAdapter Interface**  
Both Node and browser adapters now use async methods for encryption and decryption.
- **Improved Exports**  
Adapters are now imported via subpaths (`/node`, `/browser`). The main entry only exports cross-platform code (e.g., `create`), making it possible to use the library in web apps.
- **PKP & Custom Signer Support**  
Supports traditional wallet private key signers and works with PKP and custom signers.
- **Bug Fixes**  
Fixed the Authority parameter in the Lit Action access validation, preventing `.did is not a function` errors.
Fixed decryption invocation …

feat!: browser encryption adapter + pkp signing for encryption client

---

.nx/version-plans/version-plan-1751881697212.md
packages/w3up-client/README.md
packages/w3up-client/READMOAR.md

* Pulls out the verbose explainer texts to a seperate markdown document
* Users have to scroll far less to see the usage infor and API reference documentation
* Add a simple example for using the client library
* Updates existing examples
* Updates the discord URL
* Fixes login method name `authorize` -> `login`
* Adds missing client constructor options type
[📖 PREVIEW](https://github.com/storacha/upload-service/blob/703c73a6f33f7c236f11befdd809bfd1328c3fba/packages/w3up-client/README.md)

docs: make the client docs a lot better

---

.nx/version-plans/version-plan-1753095040760.md
packages/cli/bin.js
packages/cli/index.js
packages/upload-client/package.json
packages/upload-client/src/deduplication.js
packages/upload-client/src/index.js
packages/upload-client/src/types.ts
packages/upload-client/test/deduplication.test.js
packages/upload-client/test/helpers/stream.js
packages/upload-client/test/index.test.js
packages/w3up-client/README.md

This PR adds a new option `dedupe: boolean` which is `true` by default.
When `true`, the client will keep track of the CIDs of blocks that have been uploaded and will not add blocks that have already been seen to the uploaded CAR shards.
If your dataset contains a bunch of repeated files/data then this can reduce upload size and increase upload speed.

feat: block deduplication

---

packages/console/src/components/IframeAuthenticator.tsx

`window.postMessage()` events: Have an origin property for security validation - I was using that before the refactor to `MessageChannel`. Locally, it works fine, but in Staging, it started denying the messages from `https://staging.console.storacha.network`.
`MessagePort events`: Do NOT have an origin property because the security is established when the MessageChannel is created and ports are transferred. This is more secure than validating the origin because only the validated origin has the port to send messages.

fix(console): origin verification for msg channels

---

packages/access-client/src/agent.js
packages/access-client/src/types.ts
packages/access-client/test/agent.test.js
packages/access-client/test/helpers/utils.js
packages/console/src/app/settings/page.tsx

The client sometimes uses `agent.invokeAndExecute(...)` or `agent.invoke(...)`, which by default scopes session proofs to the invocation audience or `connection.id`. If the invocation audience or `connection.id` is `did:web:web3.storage` and the session proof was issued by `did:web:up.storacha.network` then the session proof will not be included in the invocation and it will fail.
This PR alters the access client to scope session proofs to the invocation audience or `connection.id` as well as any alias DIDs the service is known by.
Due to the default values for service identities there should be no code/config changes necessary to apps using the client - just a dependency update.
Apologies, no tests yet, but I _think_ this should resolve the issue.

fix(access): include session proofs issued by service aliases in invocations

---

packages/console/src/components/PlanGate.tsx

this used to work accidentally because we would render the plan picker for any error, but I broke it in my recent change in a way that prevents new users from picking a plan in the app
fortunately this hasn't totally broken login because users can still pick a plan in the auth email they get, and probably usually do, but it's a pretty serious regression.
I've tested this pretty well manually, hoping to push asap!

fix: detect "plan not found" errors correctly

---

.github/workflows/console-deploy.yml

The DMAIL team is testing the iframe integration at `https://testmailhu9fg9h.dmail.ai/workspace`, and it is getting blocked.
Enable the wildcard support for DMAIL subdomains in the Staging environment.

fix(console): wildcard subdomain for dmail in staging

---

.github/workflows/console-deploy.yml
packages/console/src/lib/sso-origins.ts

> The frame-ancestors directive in a Content Security Policy (CSP) does not support *.domains without the schema. 
It's used to control which parent pages can embed your page in an <iframe>, <frame>, <object>, <embed>, or <applet>. 
While * (without quotes) allows any origin to embed your page, using it with frame-ancestors is generally discouraged due to security risks. For specific domains, list them individually with their protocol (e.g., https://example.com).

fix(console): allow wildcard subdomain for dmail integration

---

.nx/version-plans/version-plan-1755686805318.md
packages/upload-api/src/blob/replicate.js
packages/upload-api/src/test/external-service/storage-node.js
packages/upload-api/src/test/handlers/space/blob/replicate.js

The upload service was not attaching the location commitment to the onward `blob/replica/allocate` invocation(s).
This PR updates the mock storage node implementation to check it has been attached, and the `space/blob/replicate` handler to actually attach the claim.

fix: attach location commitment to replica allocate invocation

---

packages/console/src/hooks/useFileDecryption.ts

The `DecryptDelegation` should not include the `plan/get` proof because it is not part of the invocation. The `plan/get` delegation must be passed as part of the `proofs` parameter in the decryption config. 
In another PR it will be refactored to attach the `plan/get` delegation into the `space/content/key/decrypt` invocation.

fix: decrypt delegation should not include plan/get proof 

---

packages/console/src/components/IframeAuthenticator.tsx

This reverts commit f26a3c646a951748977fb8edddd93e102b9c69ac.
I won't apply this change in production. My attempt to automatically clear user data on account switch caused state management problems, especially with SWR caches. This resulted in a flaky app experience and mixed account data.

fix: "revert feat: auto-clean user session and continue with SSO flow (#397)"

---

packages/upload-api/src/types/revocations.ts

Adds comments to clarify the fields in the `Revocation` type.

docs: clarify revocation fields

---

packages/console/src/app/iframe/layout.tsx
packages/console/src/components/Authenticator.tsx
packages/console/src/components/IframeAuthenticator.tsx
packages/console/src/components/SpaceEnsurer.tsx

Users authenticating via iframe integration are blocked when an email mismatch is detected between their session storage and the AUTH DATA provided by the provider (DMAIL). This forced users to manually clean up their local storage and try again. Ideally, we should remove this manual process to make it easier for users to interact with Storacha.
Implemented automatic email mismatch detection and cleanup:
- **Auto-detect mismatch**: Compare the current email from local storage with the expected SSO email provided by DMAIL for authentication
- **Automatic cleanup**: Clear localStorage, sessionStorage, IndexedDB, and caches
- **Seamless flow**: Logout → cleanup → authenticate with new account (no user input required)
- **Better UX**: Replaced blank pages with consistent loading screens using …

feat: automatically handle email mismatch in iframe SSO authentication

---

.nx/version-plans/version-plan-1757329417028.md
packages/upload-api/src/blob/lib.js

Fixes:
```
RangeError: Maximum call stack size exceeded
at _EntryNotFound.toString (<anonymous>)
at _EntryNotFound.describe (/Users/alan/Code/storacha/upload-service/node_modules/.pnpm/@ucanto+core@10.4.0/node_modules/@ucanto/core/src/result.js:65:17)
at _EntryNotFound.get message [as message] (/Users/alan/Code/storacha/upload-service/node_modules/.pnpm/@ucanto+core@10.4.0/node_modules/@ucanto/core/src/result.js:68:17)
at _EntryNotFound.toString (<anonymous>)
at _EntryNotFound.describe (/Users/alan/Code/storacha/upload-service/node_modules/.pnpm/@ucanto+core@10.4.0/node_modules/@ucanto/core/src/result.js:65:17)
at _EntryNotFound.get message [as message] (/Users/alan/Code/storacha/upload-service/node_modules/.pnpm/@ucanto+core@10.4.0/node_modules/@ucanto/core/src/result.js:68:17)
at …
```

fix: infinite recursion on EntryNotFound and EntryExists error messages

---

packages/console/src/app/space/[did]/root/[cid]/page.tsx
packages/console/src/components/Uploader.tsx
packages/console/src/components/services.ts
packages/console/src/hooks/useFileDecryption.ts
packages/console/src/share.tsx

This PR adds an initial implementation of the **Access Revocations** as part of the [Revocations Check in UCAN KMS](https://github.com/storacha/ucan-kms/pull/14) for DMAIL integration. The goal is to enable users to revoke delegations and confirm that revoked access is enforced.
* Added a `Revoke` button to the **Shared With** panel.
* Clicking the button revokes the delegation created by the current agent.
* Revoked access is displayed in the panel below.
* Verified that a DMAIL user attempting to decrypt after revocation receives the error:
```
Decryption failed: Delegation revoked
```
* Revocation only works when performed by the **same agent** that created the delegation. Delegations created by Agent A cannot be revoked by Agent B, even if both belong to the same account/did\:mailto. …

feat: access revocation

---

packages/console/src/components/SidebarLayout.tsx
packages/console/src/components/SpacesList.tsx

Fixes the scrolling behavior in the Sotracha Console where the sidebar and navbar would scroll out of view when there was overflow content.
- When there were many spaces or content, a vertical scrollbar would appear
- Scrolling anywhere on the screen would move both the sidebar and navbar, causing them to slide out of view
- The entire page would scroll instead of just the content areas
- This made navigation difficult when dealing with large amounts of content
- **Fixed Sidebar**: Made the sidebar `fixed` positioned so it stays in place at all times
- **Sticky Navbar**: Ensured navigation bars remain visible during content scrolling
- **Content-Only Scrolling**: Limited scrolling to specific content areas using `overflow-y-auto`
- **Layout Structure**: Updated the main layout to use …

Fix(Console UI): Keep Sidebar & Navbar Fixed, Enable Content-Only Scrolling
